# Generated by Django 5.2.10 on 2026-01-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('intro_answer', models.TextField(blank=True)),
                ('technical_answer', models.TextField(blank=True)),
                ('problem_answer', models.TextField(blank=True)),
                ('communication_answer', models.TextField(blank=True)),
                ('final_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
