# Generated by Django 5.2.10 on 2026-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
