# Generated by Django 5.2.10 on 2026-02-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_answer_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='decision',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
