# Generated by Django 5.2.10 on 2026-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_candidate_decision_candidate_hr_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='communication_answer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='intro_answer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='problem_answer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='technical_answer',
        ),
        migrations.AddField(
            model_name='candidate',
            name='conversation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='conversation_version',
            field=models.IntegerField(default=1),
        ),
    ]
