# Generated by Django 5.2.10 on 2026-02-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_remove_candidate_communication_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='conversation_version',
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_stage',
            field=models.CharField(default='INTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='questions_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='conversation',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
