# Generated by Django 5.2.10 on 2026-02-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_remove_candidate_conversation_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='interview_stage',
        ),
    ]
