# Generated by Django 5.2.10 on 2026-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_remove_candidate_interview_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pending_ai_audio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pending_ai_text',
            field=models.TextField(blank=True),
        ),
    ]
