# Generated by Django 5.2.10 on 2026-02-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_candidate_pending_ai_audio_candidate_pending_ai_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='pending_ai_text',
        ),
    ]
