# Generated by Django 5.2.10 on 2026-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_remove_candidate_pending_ai_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='pending_ai_audio',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='questions_asked',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='conversation',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
