# Generated by Django 5.2.10 on 2026-02-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_remove_candidate_pending_ai_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='call_sid',
            field=models.CharField(default='<function uuid4 at 0x74e0a8f36dd0>', max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('phone', 'call_sid')},
        ),
    ]
