# Generated by Django 5.2.10 on 2026-02-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_candidate_call_sid_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='call_sid',
        ),
    ]
