# Generated by Django 5.2.10 on 2026-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_alter_candidate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
