# Generated by Django 5.2.10 on 2026-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_candidate_questions_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='awaiting_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_turn_id',
            field=models.IntegerField(default=0),
        ),
    ]
