# Generated by Django 5.2.10 on 2026-02-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_candidate_awaiting_answer_candidate_current_turn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='awaiting_answer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_turn_id',
        ),
    ]
